# Generated by Django 3.2.22 on 2024-04-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_in_magical_website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_date', models.DateTimeField(auto_now_add=True)),
                ('profile_picture_url', models.URLField(blank=True, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('verified_through_auth_provider', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=700)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('otp_created_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(related_name='magical_website_users', to='auth.Group')),
                ('user_permissions', models.ManyToManyField(related_name='magical_website_user_permissions', to='auth.Permission')),
            ],
        ),
    ]
