# Generated by Django 3.2.22 on 2024-04-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_in_magical_website',
            old_name='name',
            new_name='username',
        ),
    ]
