# Generated by Django 3.2.22 on 2024-04-06 13:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_in_magical_website',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=700),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_in_magical_website',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
