# Generated by Django 3.2.22 on 2024-04-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0002_auto_20240406_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_in_magical_website',
            options={},
        ),
        migrations.AlterModelManagers(
            name='user_in_magical_website',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='user_in_magical_website',
            name='username',
        ),
    ]
