# Generated by Django 3.2.22 on 2024-04-11 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0002_rename_name_user_in_magical_website_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_in_magical_website',
            old_name='username',
            new_name='name',
        ),
    ]
