# Generated by Django 3.2.22 on 2024-04-10 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0003_auto_20240406_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_in_magical_website',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
