# Generated by Django 3.2.22 on 2024-04-11 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0003_rename_username_user_in_magical_website_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_in_magical_website',
            old_name='name',
            new_name='username',
        ),
    ]
