# Generated by Django 3.2.22 on 2024-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Magical_first_website', '0004_alter_user_in_magical_website_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_in_magical_website',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_in_magical_website',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
