# Generated by Django 4.2.5 on 2023-10-04 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_network'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='followers',
            new_name='follower',
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
    ]
